name: JunctionPVP
version: 1.0-SNAPSHOT
description: Junction PVP Plugin for Revision 2
author: [zifnab06]
website: http://github.com/junctionat/JunctionPVP

main: at.junction.pvp.JunctionPVP
database: false

commands:
  teams:
    description: View a list of teams, online team members, and scores.
    permission: junction.pvp.teams
    usage: /teams
  forceteam:
    description: Force a player to a given team
    permission: junction.pvp.team.add
    usage: /forceteam player teamname
  removeteam:
    description: Removes a player from any assigned teams
    permission: junction.pvp.team.remove
    usage: /removeteam player
  printteam:
    description: Print team info
    permission: junction.pvp.team.print
    usage: /printteam

permissions:
  junction.pvp.teams:
    description: Allows a player to list teams
    default: true
  junction.pvp.tech:
    description: tech/debug access
    default: op
    children:
      junction.pvp.team.add:
        description: Add player to team
        default: op
      junction.pvp.team.remove:
        description: Remove player from team
        default: op
      junction.pvp.team.print:
        description: Print team info to console
        default: op
