name: JunctionPVP
version: 1.0-SNAPSHOT
description: Junction PVP Plugin for Revision 2
author: [zifnab06]
website: http://github.com/junctionat/JunctionPVP
depend: [WorldGuard]

main: at.junction.pvp.JunctionPVP
database: false

commands:
  teams:
    description: View a list of teams, online team members, and scores.
    permission: junction.pvp.teams
    usage: /teams
  team-set:
    description: Force a player to a given team
    permission: junction.pvp.team.set
    usage: /team-set player teamname
  team-remove:
    description: Removes a player from any assigned teams
    permission: junction.pvp.team.remove
    usage: /team-remove player
  team-print:
    description: Print team info
    permission: junction.pvp.team.print
    usage: /team-print
  team-addpoint:
    description: Adds point(s) to a team. Use negatives to remove points.
    permission: junction.pvp.team.points
    usage: /team-addpoint [<value>]
  player-printmetadata:
    description: Prints relevant metadata
    permission: junction.pvp.team.metadata
    usage: /player-printmetadata <player>
permissions:
  junction.pvp.teams:
    description: Allows a player to list teams
    default: true
  junction.pvp.tech:
    description: tech/debug access
    default: op
    children:
      junction.pvp.team.set:
        description: Set player's team
        default: op
      junction.pvp.team.remove:
        description: Remove player from team
        default: op
      junction.pvp.team.print:
        description: Print team info to console
        default: op
      junction.pvp.team.metadata:
        description: Print relevant metadata
        default: op
  junction.pvp.team.points:
    description: Allows changing points of teams
    default: op

